### ISSUE TITLE
Frontend for Homepage

### ISSUE THREAD

**Issue by AidanHoremans** [laingkob/CMPUT404-project-socialdistribution#21]
As an author, after I sign in I want to be able to view my stream at the root directory which is filled with posts in my inbox.

**Comment by laingkob** [comment]
- [ ] Posts show
- [ ] Likes show
- [ ] Comments show
- [ ] (OPT) Filtered views

**Comment by laingkob** [comment]
- [ ] Feed (“stream”) is default 
- [ ] has my posts
- [ ] has my github activity

- [ ] Follow requests show

**Comment by laingkob** [comment]
Above comments to be split into separate issues
